language: ruby
before_script:
- bundle exec rake test_app
- cd spec/dummy/
- bundle exec rails g delayed_job:active_record
- RAILS_ENV=test bundle exec rake db:migrate
- cd ../..
script: bundle exec rspec
env:
- DB=sqlite3
- DB=mysql
rvm:
- 1.9.3
notifications:
  hipchat:
    rooms:
      secure: DHLoTFsbeJd5vgos1k85hGOiJ1+DL2T6SYvWlxvxhMr6beDh4FNO/kwBwyIIUIsNuzYBtZTAq2qi3dgrXBCF5WpOqHK9FNow0YWuhO/4QwnuSeMwf8SmyJzXYg0GQo+tc5pDWgqABeXtv3H1NBZkKIYkYdH9/PfO8yMvieZSSNg=
